<%@ Page Title="Pedido" Language="C#"  MasterPageFile="~/Site.Master"  AutoEventWireup="true" CodeBehind="Pedido.aspx.cs" Inherits="TrabalhoModelo.WebForm.Paginas.Pedido" %>
<%@ Register Src="~/Componentes/ResumoPedido.ascx" TagPrefix="comp" TagName="ResumoPedido" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <hr/>
    <comp:ResumoPedido runat="server" ID="cpnResumoPedido" Visible="false"></comp:ResumoPedido>
    <hr/>    
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label for="ddlCliente">Cliente:</label>
                <asp:DropDownList AutoPostBack="true"  ID="ddlCliente" runat="server" OnSelectedIndexChanged="ddlCliente_SelectedIndexChanged" />
            </div>
        </div>
    </div>
    <div>
        <div>
            <div class="form-group">
                <label for="ddlFormapagamento">Forma Pagamento:</label>
                <asp:DropDownList  AutoPostBack="true" OnSelectedIndexChanged="ddlFormapagamento_SelectedIndexChanged" ID="ddlFormapagamento" runat="server" />
            </div>
        </div>
        <div>
            <div class="form-group">
                <label for="ddlTipoFrete">Frete:</label>
                <asp:DropDownList  ID="ddlTipoFrete" runat="server" />
            </div>
        </div>
    </div>
    <fieldset>
        <legend>Itens produtos</legend>
            <div>
                <div class="form-group">
                    <label for="txtNome">Produto:</label>
                    <asp:DropDownList  AutoPostBack="true" ID="ddlProduto" runat="server" />
                </div>
            </div>
            <div >
                <div class="form-group">
                    <label for="txtNome">Quantidade:</label>
                    <asp:TextBox  runat="server" ID="txtQuantidadeitens" TextMode="Number" />
                </div>
            </div>
            <div >
                <div class="form-group">
                    <asp:Button runat="server" ID="btnAdicionarProduto" OnClick="btnAdicionarProduto_Click" Text="Adicionar" />
                </div>
            </div>
        <div>
            <asp:GridView ID="grdItensPedido" runat="server"   AutoGenerateColumns="false" AutoGenerateDeleteButton="true"
                OnRowDeleting="grdItensPedido_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="Identificador" HeaderText="Identificador" />
                    <asp:BoundField DataField="Descricao" HeaderText="Produto" />
                    <asp:BoundField DataField="Total" HeaderText="Total" />
                </Columns>
            </asp:GridView>
        </div>
    </fieldset>
    <hr />
    <div runat="server">
        <asp:Button runat="server" ID="btnComprar" OnClick="btnComprar_Click" Text="Comprar" />
    </div>
</asp:Content>
