<%@ Page Title="Produtos" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Produtos.aspx.cs" Inherits="TrabalhoModelo.WebForm.Paginas.Produtos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <hr/>
    <h3>Listagem</h3>
    <asp:GridView ID="grdDados" runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="grdDados_RowDeleting" AutoGenerateColumns="false"  >
        <Columns>
            <asp:BoundField DataField="Identificador" HeaderText="Identificador" />
            <asp:BoundField DataField="Descricao" HeaderText="Descrição" />
            <asp:BoundField DataField="PrecoVenda" HeaderText="Preço Venda" />
        </Columns>
    </asp:GridView>
    <hr />
    <div>
        <div class="form-group">
            <label for="txtNome">Descrição:</label>
            <asp:TextBox  runat="server" ID="txtDescricao" />
        </div>
    </div>
    <div>
        <div class="form-group">
            <label for="txtNome">Preço:</label>
            <asp:TextBox  runat="server" ID="txtPreco" TextMode="Number" />
        </div>
    </div>
    <asp:Button   runat="server" ID="btnSalvar" OnClick="btnSalvar_Click" Text="Salvar" />    
</asp:Content>
